version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: url_shortener_postgres
    environment:
      POSTGRES_DB: tinyurl_db
      POSTGRES_USER: tinyuser
      POSTGRES_PASSWORD: StrongPassword123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    container_name: url_shortener_redis
    ports:
      - "6379:6379"

volumes:
  pgdata: